name: Generate Changelog

on:
  push:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Set up Git user
        run: |
          git config --global user.name "thornbug90"
          git config --global user.email "crazydev0409@gmail.com"
      - name: Commit and push changes
        run: |
          npx semantic-release

        # # git add CHANGELOG.md
        # git commit -m "Update Changelog"
        # git push
